name: Docker build

on:
  push:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar repositorio
              run: action/checkout@v4

            - name: Construir imagen
              run: docker build -t node-test:1 .